<<<<<<< Updated upstream
# Site settings
title:       Taylor Xu
email:       taylorhxu@gmail.com
author:      Taylor Xu
description: "Technology, above and beyond."
baseurl:     ""
url:         "http://taylorhxu.github.io"
date_format: "%b %-d, %Y"
=======
### your site title here
>>>>>>> Stashed changes

title: Hagura - Light!
baseurl: /hagura # name of the repository

highlighter: rouge
markdown: kramdown
### exclude the instructions / write-up in the README.md



<<<<<<< Updated upstream
# Social icons
github_username: taylorhxu
bitbucket_username:
stackoverflow_id: 
twitter_username: taylorhxu
skype_username:
steam_nickname:
google_plus_id: 
linkedin_username: taylorhxu
angellist_username:
medium_id: taylorhxu
bitcoin_url:
paypal_url:
flattr_button:
=======
# Tracker
analytics: UA-83979019-1
>>>>>>> Stashed changes

#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []
  

sass:
 style: compressed

exclude:
- README.md


gems: [jekyll-seo-tag, jekyll-paginate]
