# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Taylor Xu
tagline:             'All about tech, above and beyond.'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://taylorhxu.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Taylor Xu
  url:               https://twitter.com/taylorhxu
  email:             taylorhxu@gmail.com

# Custom vars
version:             1.0.0
