name: Taylor Xu
description: Biomedical engineer, technologist, photography enthusiast, minimalist, coffee addicted and former London 2012 cast
meta_description: "Technology enthusiast"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 5
baseurl: /
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-XXXXXXXX-X'

# Details for the RSS feed generator
url:            'blog url'
author:         'Taylor Xu'
