# Site settings
title: Taylor Xu
email: taylor.h.xu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Engineering, Technology and Photography.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: taylorhxu
github_username:  taylorhxu

# Build settings
markdown: kramdown
