# Site settings
title: Taylor H Xu
description: >
  Aspiring biomedical engineer, music 

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://taylorhxu.com" # the base hostname & protocol for your site

author:
  fullname: Taylor H Xu
  googleplus: https://plus.google.com/+TaylorXutaylorhxu/
  github: taylorhxu
  twitter: taylorhxu
  # disqus: your_disqus_username

# google_analytics: 'UA-55488001-1'

# Build settings
markdown: kramdown