<<<<<<< HEAD
markdown: rdiscount
pygments: true
safe: false
=======
# Site settings
title:       Taylor Xu
email:       taylor.h.xu@gmail.com
author:      Taylor Xu
description: "I am a biomedical engineer, technologist, photography enthusiast, minimalist, coffee addicted and former London 2012 cast."
baseurl:     ""
url:         "taylorhxu.com"
>>>>>>> FETCH_HEAD

name: Taylor Xu
description: Technology enthusiast.
meta_description: "Technology enthusiast"

logo: false
paginate: 5
baseurl: /
domain_name: 'http://taylorhxu.com'
google_analytics: 'UA-55488001-1'

# Details for the RSS feed generator
name:           Taylor Xu
url:            'http://taylorhxu.com'
author:         'Taylor Xu'
