markdown: rdiscount
pygments: true
safe: false

name: Taylor Xu
description: Technology enthusiast.
meta_description: "Technology enthusiast"

logo: false
paginate: 5
baseurl: /
domain_name: 'http://taylorhxu.com'
google_analytics: 'UA-55488001-1'
paginate_per_category: true 

# Details for the RSS feed generator
name:           Taylor Xu
url:            'http://taylorhxu.com'
author:         'Taylor Xu'
