# Site settings
title:       Taylor Xu
email:       taylor.h.xu@gmail.com
author:      Taylor Xu
description: "I am a biomedical engineer, technologist, photography enthusiast, minimalist, coffee addicted and former London 2012 cast."
baseurl:     "taylorhxu.com"
url:         "taylorhxu.com"

# Google analytics
google_analytics:

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: taylorhxugj

# Social icons
show_social_icons: true
github_username: taylorhxu
stackoverflow_id:
twitter_username: taylorhxu
google_plus_id:
linkedin_username: taylorhxu
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true
