title:            TAYLEGRAM by Taylor Xu
description:      A Jekyll blog by Taylor.
url:              # Site url.
signoff:          Taylor Xu
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Email
    url:          mailto:taylor.h.xu@gmail.com
    external:     true
  - name:         GitHub
    url:          http://github.com/taylorhxu
    external:     true
  - name:         Photography
    url:           http://taylorhxu.com
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
