# Site settings
title: Taylor Xu
email: taylor.h.xu@gmail.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://taylorhxu.giyhub.io"
twitter_username: taylorhxu
github_username:  taylorhxu
facebook_username:  taylorhxu

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]