# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               Misc Taylor
tagline:             'personal wiki in progress'
description:         ''
url:                 http://taylorhxu.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Taylor Xu
  url:               https://twitter.com/taylorhxu
  email:             taylorhxu@gmail.com

# Custom vars
version:             1.0.0
