# Site settings
title:       Taylor Xu
email:       taylor.h.xu@gmail.com
author:      Taylor Xu
description: "A simple, beautiful theme for Jekyll that emphasizes content rather than aesthetic fluff."
baseurl:     ""
url:         "taylorhxu.com"

# Google analytics
google_analytics:

# Optional features
animated:           true
show_related_posts: true
show_post_footers:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: true
github_username: taylorhxugj
stackoverflow_id:
twitter_username: taylorhxu
google_plus_id:
linkedin_username: taylorhxu
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true
