# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Taylor H. Xu
tagline:             Technology enthusiast
description:         Biomedical engineer, technologist, photography enthusiast, minimalist, coffee addicted and former London 2012 cast.
url:                 #
baseurl:             /
paginate:            2

# About/contact
author:
  name:              Taylor Xu
  url:               https://twitter.com/taylorhxu
  email:             taylor.h.xu@gmail.com

# Custom vars
version:             1.0.0
