# Site settings
title: Taylor H. Xu
email: taylorhxu@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site

# Sidebar settings
description: One sentence introducing yourself or what you do

# Social icons
facebook: taylorhxu
linkedin: taylorhxu
github: taylorhxu
deviantart: username
codepen: username

footer: © Taken theme

# Build settings
markdown: kramdown
