title: 	Taylor Xu
description: "Technology, above and beyond."

url: http://taylorhxu.github.io
port: 3000
highlighter: pygments

permalink: /:year/:month/:day/:title.html
markdown: redcarpet

google_analytics: #

owner:
  name: Taylor Xu
  disqus_shortname: taylorhxugj
  twitter: taylorhxu
