# Site settings
title: Taylor Xu
email: taylorhxu@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site

# Sidebar settings
description: "music, techno, BME, DIY, data, photography, above and beyond."
# Social icons
facebook: taylorhxu
linkedin: taylorhxu
github: taylorhxu
twitter: taylorhxu

footer: © Taken theme

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
