# Site settings
title:       Taylor H. Xu
email:       taylor.h.xu@gmail.com
author:      Taylor Xu
description: "Technology enthusiast"
baseurl:     "http://taylorhxu.com"
url:         "http://taylorhxu.com"

# Google analytics
google_analytics: UA-55488001-1

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: taylorhxugj

# Social icons
show_social_icons: true
github_username: taylorhxu
stackoverflow_id: 
twitter_username: taylorhxu
google_plus_id: +TaylorXutaylorhxu
linkedin_username: taylorhxu
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     5
sass:
  compressed: true
