markdown: rdiscount
pygments: true
safe: false

name: Taylor Xu
description: Biomedical engineer, technologist, photography enthusiast, minimalist, coffee addicted and former London 2012 cast.
meta_description: "Technology enthusiast"

logo: false
paginate: 5
baseurl: /
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-55488001-1'

# Details for the RSS feed generator
name:           Taylor Xu
url:            'blog url'
author:         'Taylor Xu'
